name: "✨ Feature request"
description: Suggest an idea or enhancement
title: "feat: <short description>"
labels:
  - enhancement
  - needs-triage
  - help-wanted
  - hacktoberfest
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for proposing a feature! Please search existing issues first.
  - type: input
    id: summary
    attributes:
      label: Summary
      description: A concise description of the feature
      placeholder: e.g., Add dark mode toggle in settings
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What problem does this feature solve?
      placeholder: Describe the user problem or job-to-be-done
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe your proposed solution or API
      placeholder: |
        A clear and concise description of what you want to happen
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Have you considered any alternative solutions or features?
    validations:
      required: false
  - type: textarea
    id: scope
    attributes:
      label: Out of scope
      description: What is explicitly out of scope?
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      placeholder: Links, screenshots, prior art, etc.
    validations:
      required: false

